### ISSUE TITLE
Allow scheduling repository imports.

### ISSUE THREAD

**Issue by kallisti5** [haiku/haikudepotserver#152]
Exposing __repository/haikuports/import to the world could be a serious vulnerability... do we queue these requests? Could someone DDOS the server by hitting it over and over?

We may want to allow scheduling repository imports within Haiku Depot Server.  While this won't remove the need for import hooks (they could be handy per-commit), it would help reduce the need.

**Comment by aplgithub** [comment]
> Exposing __repository/haikuports/import to the world c...DDOS...

The HPKR import requests are queued, but the queue is presently in-memory only.  The requests are however coalesce so that if there is a request queued already then it will not enqueue another one.  However, yes probably some sort of authentication would probably be good here.  I will add a form of Basic authentication to this and the maintenance task endpoints as part of this ticket.

> We may want to allow scheduling repository imports within Haiku Depot Server.

There are two maintenance tasks that can be initiated with an HTTP GET request;

|Task|Endpoint|
|---|---|
|Daily|```/__maintenance/daily```|
|Hourly|```/__maintenance/hourly```|

Those should be configured to run from ```cron``` or similar.  The "Daily" task will import HPKR data for all repositories.  This ensures that even if the repositories' own triggering mechanics do not work then at least HDS reads all HPKRs each day.  If you re-enable the crons from somewhere then this will start happening.

I could build this into HDS using [Quartz](http://www.quartz-scheduler.org/) but IMHO it is easier to trigger from an external scheduler system such as ```cron``` for now.

**Comment by aplgithub** [comment]
As requested, I have now changed the HDS system so that it uses an internal application-server scheduler for scheduled-maintenance.  The external triggers (over REST) will remain in place for one deploy and will later be retracted so they return 404s.  I don't know if this is a good change because of the later complexities of ensuring a single-master in an active-active redundant deployment would seem less than using cron as an external scheduler, but evidently it is easier for now and it won't be too hard to change later.  This is in the 'snapshot' and will go into the next deployment.

**Comment by aplgithub** [comment]
I have added the ability to add a password per Repository that will protect the API calls with Basic authentication.  This will not be configured initially without passwords and @kallisti5 - I will leave you to add those passwords and coordinate the changes with the Repository owners.

Also in this change is the ability to add a "forced internal API" for the Repository Source.  When HDS pulls down data from the Repository Source (HPKR data) then it will use this internal URL instead of using the main mirror.  This gets around the Docker network issue.  The deployment will take care of fixing the existing data; some checks should be undertaken post-deployment around this.

These changes are in the snapshot and will go into the next deployment.
