### ISSUE TITLE
Don't upload icons for not enabled repos

### ISSUE THREAD

**Issue by diversys** [haiku/haikudepotserver#180]
HaikuDepot downloads all of HDS icons, however most people use have default repos enabled.
This will save some disk space as well as speed up resource downloading. This could also possibly reduce HaikuDepot memory usage that is currently ~60MB.

**Comment by aplgithub** [comment]
It is correct that the desktop application HaikuDepot (HD) will download all available icons from HaikuDepotServer (HDS) in one download.

## Memory Footprint

The suggested approach will not reduce HD memory (RAM) consumption because only those icons that are associated with a package are actually loaded into memory.  (related; What is more likely to help with memory consumption and speed is on-demand load icon images and discarding icon images when they are no longer being viewed.  I'd like to spend some time on that when I get the opportunity.)

## Disk Footprint

Because packages can appear in more than one repository there are some complexities around caching and cache-eviction of the icon data between HD and HDS.  This maybe quite difficult to deal with both on the HD and the HDS side and so it would be helpful to first understand how much data is stored client-side for HD that is not used when, for example, the user only has HaikuPorts configured.

Are you able to find the time to establish both the quantity of unused files and the quantity of unused data involved in this case?  It would also be helpful to know the "tar.gz" payload size with and without that unused data.

**Comment by aplgithub** [comment]
I just loaded HD desktop application with no network access and hence no data from HDS and it is consuming circa 56MB.  Add in full data from HDS and that appears to be circa 66MB.  Without icons loaded via a modified build product that comes to circa 58MB.  From this I presume it would be reasonable to assume that the runtime overhead of the meta-data is ~2MB and the runtime overhead of the icons is ~8MB.

**Comment by diversys** [comment]
Indeed, I did the same test some time ago. So it looks like something else is using so much memory.

**Comment by aplgithub** [comment]
Can I close this one; it doesn't seem to be a problem?

**Comment by diversys** [comment]
Can we measure how much bugger the archive with all of the icons is compared to archive with icons only from haikuports repo? Maybe it's worth splitting them up?

**Comment by aplgithub** [comment]
Yes, you should be able to easily get a list of package names from the repository, download the tar-ball from [here](https://depot.haiku-os.org/__pkgicon/all.tar.gz), filter for the packages you want and thereby establish the sizing.

**Comment by diversys** [comment]
How do I get a list of package names from the repository?

BTW, I measured time needed to unpack the tar-ball and it's 6.5 sec under VMware which is not very efficient I think?
```
time tar xzfv all.tar.gz
real    0m6.568s
user    0m0.172s
sys     0m1.585s
```

**Comment by aplgithub** [comment]
> How do I get a list of package names from the repository?

You can extract it from the `HPKR` file on your Haiku machine or you can extract it from the JSON [here](https://depot.haiku-os.org/__pkg/all-haikuports_x86_64-en.json.gz).

> I measured time needed to unpack the tar-ball and it's 6.5 sec

I have a plan to not unpack the tar file, but to index it instead.  See [here](https://dev.haiku-os.org/ticket/15370) for some discussion about this.  However this won't happen for a while.

**Comment by aplgithub** [comment]
I don't think it makes sense to split the download up into different `tar.gz` downloads because that will make it difficult to track situations where the same icon appears in multiple places.  The memory issue is no longer a concern because the icon download and quasi-unpack has [changed](https://www.haiku-os.org/blog/apl/2020-11-16_haikudepot_better_icons/) considerably in recent months.  I don't think this ticket is relevant any more?

**Comment by diversys** [comment]
Since HD doesn't unpack the tar file anymore I think it makes sense to close it.
